set AzureWebJobsDashboard=DefaultEndpointsProtocol=https;AccountName=fagorederlanfunctions;AccountKey=GVmE8oud1p12zJUksUIdbC4S5hSN9A+vhQhk5orJ9MWZQS43rSEpyZC0odp3R3Mmvu8ljzg0mU6/TjO+/gRU8w==
set AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=fagorederlanfunctions;AccountKey=GVmE8oud1p12zJUksUIdbC4S5hSN9A+vhQhk5orJ9MWZQS43rSEpyZC0odp3R3Mmvu8ljzg0mU6/TjO+/gRU8w==
set fagorederlanfiles_STORAGE=DefaultEndpointsProtocol=https;AccountName=fagorederlanfiles;AccountKey=+DSWcEcfRLwe3oZgGpbXyT1wAY2pomVGpPWPTnbCZr7OpwnMSqenHjaBX2UBg81j/kA6X3/wPpcDNNSE4zZD0w==
